network:
  collector_uri: "ws://89.104.71.190:8001/ws"
  server_host: "0.0.0.0"
  server_port: 9999

database:
  host: "localhost"
  port: "6379"

logger:
  log_level: "info"
  log_file: "news_processor.log"