network:
  collector_uri: "ws://89.104.71.190:8001/ws"
  wsserver:
    host: "0.0.0.0"
    port: 9999
  restserver:
    host: "0.0.0.0"
    port: 9999

database:
  host: "localhost"
  port: "6379"

logger:
  log_level: "info"
  log_file: "news_processor.log"